name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Post comment
      uses: actions/github-script@v4.1.0
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `test`;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          });
