name: Test

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, closed ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Stderr
      id: error
      run: echo "hello"
      continue-on-error: true
    - name: Post comment
      uses: actions/github-script@v4.1.0
      env:
        out: ${{ steps.error.outputs.stdout }}
        err: ${{ steps.error.outputs.stderr }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `
            out: ${process.env.err}
            error: ${process.env.err}
          `;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          });
